// Тексты ru/en — дословно как src/i18n.ts мини-аппа (он источник формулировок, CLAUDE.md «Платформы»). Язык — как у
// человека в настройках (users.language_code), а не язык системы: его меняют в «Я», и приложение переключается сразу.
// Разделы переносятся вместе с экранами; поменяли текст в мини-аппе — меняем и здесь (и в apple/Kit Strings.swift).
package app.lifecommit.core

import java.text.DecimalFormat
import java.text.DecimalFormatSymbols
import java.time.format.DateTimeFormatter
import java.util.Locale

object Plural {
    /** Русское склонение по числу: 1 день, 2 дня, 5 дней, 11 дней, 21 день. */
    fun ru(n: Int, one: String, few: String, many: String): String {
        val m10 = Math.abs(n) % 10
        val m100 = Math.abs(n) % 100
        if (m10 == 1 && m100 != 11) return one
        if (m10 in 2..4 && m100 !in 12..14) return few
        return many
    }

    /** Английское: 1 day, 2 days. */
    fun en(n: Int, one: String, many: String): String = if (n == 1) one else many
}

class Strings private constructor(
    val lang: Lang,
    // Общее
    val loadError: String,
    val retry: String,
    val error: String,
    val today: String,
    val me: String,
    val calendar: String,
    val groups: String,
    val voiceMic: String,
    val cancel: String,
    // Вход
    val signIn: String,
    val signInSub: String,
    val signInFailed: String,
    // «Сегодня»
    val habits: String,
    val addTask: String,
    val nothingDue: String,
    val archivedLink: (Int) -> String,
    val didIt: String,
    val didItShort: String,
    val answerYes: String,
    val answerNo: String,
    val markDone: String,
    val of: String,
    val enterValue: String,
    val cleanDays: (Int) -> String,
    val schedules: Map<Schedule, String>,
    val perWeek: (Int) -> String,
    val limitReached: (Int) -> String,
    val todo: TodoStrings,
    val swipe: SwipeStrings,
    // «Чего я хочу?»
    val onboardingTitle: String,
    val onboardingHint: String,
    val onboardingSkip: String,
    val intents: Map<TaskKind, Intent>,
    // Редактор привычки
    val newTask: String,
    val editTask: String,
    val titlePh: Map<TaskKind, String>,
    val lastSlip: String,
    val notSet: String,
    val done: String,
    val goal: String,
    val repeat: String,
    val perWeekHint: (Int) -> String,
    val weekdaysShort: List<String>,
    val who: String,
    val visibility: Map<Visibility, String>,
    val add: String,
    val save: String,
    val postpone: String,
    val deleteTask: String,
    val goalTomorrow: String,
    // «Отложенные»
    val archive: String,
    val restore: String,
    val deleteForever: String,
    val deleteForeverConfirm: String,
    // Разделы, которых в приложении ещё нет (docs/parity.md «ждёт»), выход, кнопка «Назад»
    val pendingSection: String,
    val openInTelegram: String,
    val voiceSoon: String,
    val openBot: String,
    val logoutDevice: String,
    val logoutDeviceConfirm: String,
    val logoutOk: String,
    val back: String,
    val clearDate: String,
    // Экран привычки
    val cleanDaysWord: (Int) -> String,
    val goalLine: (Double, String?) -> String,
    val goalShort: String,
    val sinceDate: (String) -> String,
    val twoWeeks: String,
    val statOf: (Int, Int) -> String,
    val statPlanIn: (String) -> String,
    val statTimesIn: (String) -> String,
    val statTimesAll: String,
    val statAvg: (String?) -> String,
    val statBest: String,
    val statSumIn: (String) -> String,
    val statRunNow: String,
    val statRunBest: String,
    val statSlipsIn: (String) -> String,
    val prevMonth: String,
    val nextMonth: String,
    val markClean: String,
    val markSlip: String,
    val markNotDone: String,
    val markClear: String,
    // «Календарь»
    val day: String,
    val month: String,
    val prevDay: String,
    val nextDay: String,
    val backToToday: String,
    val calAdd: String,
    val calEmpty: String,
    val hours: String,
    val minutes: String,
    val cal: CalStrings,
    // «Вместе», карта
    val gr: GroupStrings,
    val fr: FriendStrings,
    val year: String,
    val activeDays: (Int) -> String,
) {
    enum class Lang { Ru, En }

    data class Intent(val title: String, val examples: String)

    class TodoStrings(
        val block: String,
        val blockEvents: String,
        val blockMixed: String,
        val showAll: String,
        val showLeft: String,
        val showWhich: String,
        val add: String,
        val addPh: String,
        val later: (Int) -> String,
        val laterTitle: String,
        val tomorrow: String,
        val until: (String) -> String,
        val since: (String) -> String,
        val sinceYesterday: String,
        val check: (String) -> String,
        val uncheck: (String) -> String,
        // Шторка дела
        val edit: String,
        val event: String,
        val deleteEvent: String,
        val place: String,
        val placePh: String,
        val onMap: String,
        val join: String,
        val openLink: String,
        val people: (Int) -> String,
        val andMore: (Int) -> String,
        val more: String,
        val openGoogle: String,
        val whenLabel: String,
        val today: String,
        val otherDay: String,
        val pick: String,
        val time: String,
        val allDay: String,
        val noTime: String,
        val fromApple: String,
        val fromGoogle: String,
        val delete: String,
    )

    class GroupStrings(
        val empty: String,
        val newGroup: String,
        val namePh: String,
        val create: String,
        val progress: (Int, Int) -> String,
        val people: (Int) -> String,
        val forYou: (String) -> String,
        val tabItems: String,
        val tabPeople: String,
        val todayLabel: String,
        val soon: String,
        val settings: String,
        val name: String,
        val nothingToday: String,
        val invite: String,
        val inviteHint: String,
        val inviteSent: String,
        val connectChat: String,
        val chatLabel: String,
        val chatOther: String,
        val chatOff: String,
        val chatOffConfirm: (String) -> String,
        val connectChatHint: String,
        val addItem: String,
        val newItem: (String) -> String,
        val itemPh: String,
        val eventPh: String,
        val goalPh: String,
        val who: String,
        val modes: Map<GroupMode, String>,
        val modeHints: Map<GroupMode, String>,
        val all: String,
        val me: String,
        val rotate: String,
        val eachHint: String,
        val repeat: String,
        val repeats: Map<GroupRepeat, String>,
        val date: String,
        val time: String,
        val allDay: String,
        val noTime: String,
        val target: String,
        val targetPh: String,
        val until: String,
        val add: String,
        val save: String,
        val remove: String,
        val anyone: String,
        val toYou: String,
        val toAll: String,
        val event: String,
        val turnOf: (String) -> String,
        val yourTurn: String,
        val doneBy: (String) -> String,
        val taken: String,
        val notYours: String,
        val goalOf: (String, String) -> String,
        val put: String,
        val putTitle: (String) -> String,
        val putPh: String,
        val leave: String,
        val leaveConfirm: String,
        val removeGroup: String,
        val removeConfirm: String,
        val adminsOnly: String,
        val join: JoinStrings,
    )

    class JoinStrings(
        val invites: (String) -> String,
        val invitesAnon: String,
        val what: String,
        val points: List<Pair<String, String>>,
        val btn: String,
        val later: String,
        val expired: String,
        val notFound: String,
        val already: String,
        val open: String,
    )

    class FriendStrings(
        val tabGroups: String,
        val tabFriends: String,
        val invite: String,
        val empty: String,
        val requests: (Int) -> String,
        val requestsTitle: String,
        val waiting: String,
        val cancel: String,
        val accept: String,
        val decline: String,
        val viaLink: String,
        val progress: (Int, Int) -> String,
        val search: String,
        val nothingFound: String,
        val sendLink: String,
        val shareText: String,
        val usernamePh: String,
        val call: String,
        val status: Map<PersonStatus, String>,
        val notFound: String,
        val badUsername: String,
        val remove: String,
        val block: String,
        val removeConfirm: (String) -> String,
        val blockConfirm: (String) -> String,
        val habits: String,
        val noShown: String,
        val doneToday: String,
        val countToday: (String, String, String?) -> String,
        val linkTitle: (String) -> String,
        val linkSub: String,
        val linkBtn: String,
        val linkSent: (String) -> String,
        val linkFriends: String,
        val linkSelf: String,
        val linkBlocked: String,
        val linkNotFound: String,
        val later: String,
        val open: String,
        val showTitle: String,
        val selectAll: String,
        val blocked: String,
        val unblock: String,
    )

    class CalStrings(
        val connectTitle: String,
        val connectHint: String,
        val connect: String,
        val sheetTitle: String,
        val refresh: String,
        val sheetHint: String,
        val google: String,
        val googleSoon: String,
        val googleNeeds: String,
        val googleUnverified: String,
        val googleSetup: String,
        val googleChoose: String,
        val googleExpired: String,
        val reconnect: String,
        val errGoogle: String,
        val disconnectOf: (String) -> String,
        val apple: String,
        val appleNeeds: String,
        val connected: String,
        val synced: (String) -> String,
        val justNow: String,
        val minutesAgo: (Int) -> String,
        val authFailed: String,
        val newPassword: String,
        val whatToTake: String,
        val writeTo: String,
        val disconnect: String,
        val disconnectConfirm: String,
        val appleTitle: String,
        val appleHint: String,
        val appleSteps: List<String>,
        val openAppleId: String,
        val appleLogin: String,
        val applePassword: String,
        val connecting: String,
        val errAuth: String,
        val errInput: String,
        val errNet: String,
        val noCalendars: String,
        /** Возврат после входа Google с ошибкой: denied, expired, failed → заголовок и пояснение (worker/google.ts TEXT). */
        val googleReturn: Map<String, Pair<String, String>>,
        /** Код возврата Google чужой, использованный или старше 15 минут (404, 410 у /calendars/google/finish). */
        val googleLinkExpired: String,
    )

    class SwipeStrings(
        val remove: String,
        val undo: String,
        val removed: (String) -> String,
        val hide: String,
        val hidden: (String) -> String,
        val skipped: (String) -> String,
        val sharedHint: String,
        val onlyToday: String,
        val forAll: String,
        val notAllowed: String,
    )

    val locale: Locale = if (lang == Lang.Ru) Locale.forLanguageTag("ru-RU") else Locale.US

    // Числа и даты

    /** Число: разряды через неразрывный пробел с тысяч (146, 1 146, 25 546), до двух знаков после запятой. */
    fun num(n: Double): String = number(n, lang)

    fun num(n: Int): String = number(n.toDouble(), lang)

    private fun format(day: String, pattern: String): String {
        val date = Days.date(day) ?: return day
        return DateTimeFormatter.ofPattern(pattern, locale).format(date)
    }

    /** «26 сентября» / «September 26». */
    fun dayMonth(day: String): String = format(day, if (lang == Lang.Ru) "d MMMM" else "MMMM d")

    /** «пт, 3 октября» / «Fri, October 3» — подпись стоит внутри строки, по-русски строчными. */
    fun weekdayDayMonth(day: String): String {
        val date = Days.date(day) ?: return day
        if (lang == Lang.En) return format(day, "EEE, MMMM d")
        return "${ruWeekdaysShort[date.dayOfWeek.value - 1]}, ${format(day, "d MMMM")}"
    }

    /** «октябрь» — название месяца для подписей («по плану за октябрь»). */
    fun monthName(month: String): String {
        val date = Days.date("$month-15") ?: return month
        return DateTimeFormatter.ofPattern("LLLL", locale).format(date)
    }

    /** «окт» / «Oct» — подпись месяца над картой года. */
    fun monthShort(month: String): String {
        val date = Days.date("$month-15") ?: return month
        return DateTimeFormatter.ofPattern("LLL", locale).format(date).replace(".", "")
    }

    /** «15 окт» / «Oct 15» — коротко. */
    fun dayMonthShort(day: String): String = format(day, if (lang == Lang.Ru) "d MMM" else "MMM d").replace(".", "")

    /** «Октябрь 2026» — над календарём месяца. */
    fun monthYear(month: String): String = monthName(month).replaceFirstChar { it.titlecase(locale) } + " " + month.take(4)

    /** «понедельник, 5 октября» / «Monday, October 5» — заголовок шторки отметки задним числом. */
    fun weekdayLong(day: String): String = format(day, if (lang == Lang.Ru) "EEEE, d MMMM" else "EEEE, MMMM d")

    /** Шапка «Сегодня»: «Понедельник, 5 октября» / «Monday, October 5» — с заглавной. */
    fun longDate(day: String): String =
        format(day, if (lang == Lang.Ru) "EEEE, d MMMM" else "EEEE, MMMM d").replaceFirstChar { it.titlecase(locale) }

    companion object {
        /** Сокращения дней недели, как Intl ru в мини-аппе («пт»); у JDK и Android они бывают разными. */
        private val ruWeekdaysShort = listOf("пн", "вт", "ср", "чт", "пт", "сб", "вс")

        internal fun number(n: Double, lang: Lang): String {
            val symbols = DecimalFormatSymbols(if (lang == Lang.Ru) Locale.forLanguageTag("ru-RU") else Locale.US)
            // Как Intl в мини-аппе: по-русски разряды — неразрывный пробел U+00A0 (JDK и Android дают разный), дробь — запятая.
            if (lang == Lang.Ru) {
                symbols.groupingSeparator = '\u00a0'
                symbols.decimalSeparator = ','
            }
            return DecimalFormat("#,##0.##", symbols).format(n)
        }

        fun of(languageCode: String?): Strings = if (languageCode == "en") en else ru

        val ru: Strings by lazy {
            val num = { n: Int -> number(n.toDouble(), Lang.Ru) }
            Strings(
                lang = Lang.Ru,
                loadError = "Не получилось загрузиться. Проверьте интернет и попробуйте ещё раз.",
                retry = "Ещё раз",
                error = "Что-то пошло не так. Попробуй ещё раз.",
                today = "Сегодня",
                me = "Я",
                calendar = "Календарь",
                groups = "Вместе",
                voiceMic = "Сказать голосом",
                cancel = "Отмена",
                signIn = "Войти через Telegram",
                signInSub = "Привычки, дела и группы\u00a0— те же, что в Telegram.",
                signInFailed = "Не получилось\u00a0— проверь интернет и попробуй ещё раз.",
                habits = "Привычки",
                addTask = "Добавить привычку",
                nothingDue = "На сегодня всё",
                archivedLink = { "Отложенные · $it" },
                didIt = "Сегодня получилось?",
                didItShort = "Получилось?",
                answerYes = "Да, получилось",
                answerNo = "Нет, сегодня было",
                markDone = "Сделано",
                of = "из",
                enterValue = "ввести число",
                cleanDays = { "${num(it)} ${Plural.ru(it, "день", "дня", "дней")} без этого" },
                schedules = mapOf(Schedule.Daily to "Каждый день", Schedule.Weekdays to "По дням недели", Schedule.PerWeek to "Несколько раз в неделю"),
                perWeek = { "$it ${Plural.ru(it, "раз", "раза", "раз")} в неделю" },
                limitReached = { "Бесплатно — до $it привычек. Можно отложить какую-нибудь." },
                todo = TodoStrings(
                    block = "Дела",
                    blockEvents = "События",
                    blockMixed = "События и дела",
                    showAll = "Все",
                    showLeft = "Осталось",
                    showWhich = "Какие дела показывать",
                    add = "Дело на сегодня",
                    addPh = "Что сделать?",
                    later = { "Потом · ${num(it)}" },
                    laterTitle = "Запланировано",
                    tomorrow = "Завтра",
                    until = { "до $it" },
                    since = { "с $it" },
                    sinceYesterday = "со вчера",
                    check = { "Сделано: $it" },
                    uncheck = { "Не сделано: $it" },
                    edit = "Дело",
                    event = "Событие",
                    deleteEvent = "Удалить событие",
                    place = "Место",
                    placePh = "Где?",
                    onMap = "Открыть на карте",
                    join = "Подключиться",
                    openLink = "Открыть ссылку",
                    people = { "${num(it)} ${Plural.ru(it, "участник", "участника", "участников")}" },
                    andMore = { "и ещё ${num(it)}" },
                    more = "Ещё",
                    openGoogle = "Открыть в Google Календаре",
                    whenLabel = "Когда",
                    today = "Сегодня",
                    otherDay = "Другой день",
                    pick = "Выбрать",
                    time = "Время",
                    allDay = "Весь день",
                    noTime = "Без времени",
                    fromApple = "Из Apple Календаря",
                    fromGoogle = "Из Google Календаря",
                    delete = "Удалить дело",
                ),
                swipe = SwipeStrings(
                    remove = "Удалить",
                    undo = "Вернуть",
                    removed = { "«$it» удалено" },
                    hide = "Скрыть",
                    hidden = { "«$it» скрыто" },
                    skipped = { "«$it» убрано на сегодня" },
                    sharedHint = "Дело общее и повторяется. Убрать его только сегодня или удалить у всех в группе?",
                    onlyToday = "Убрать только сегодня",
                    forAll = "Удалить для всех",
                    notAllowed = "В этой группе дела удаляют только админы",
                ),
                onboardingTitle = "Чего я хочу?",
                onboardingHint = "Выбери одно — остальное можно добавить потом",
                onboardingSkip = "Пропустить",
                intents = mapOf(
                    TaskKind.Check to Intent("Делать регулярно", "каждый день или пару раз в неделю: спортзал, уборка"),
                    TaskKind.Count to Intent("Считать что-то", "8 стаканов воды, 20 страниц"),
                    TaskKind.Abstain to Intent("Бросить", "курение, алкоголь, сладкое"),
                ),
                newTask = "Новая привычка",
                editTask = "Привычка",
                titlePh = mapOf(TaskKind.Count to "Например, читать", TaskKind.Check to "Например, сходить в спортзал", TaskKind.Abstain to "Например, не курить"),
                lastSlip = "Последний раз",
                notSet = "Не указано",
                done = "Готово",
                goal = "Цель на день",
                repeat = "Повторять",
                perWeekHint = { "${Plural.ru(it, "раз", "раза", "раз")} в неделю, в любые дни" },
                weekdaysShort = listOf("Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"),
                who = "Кто видит",
                visibility = mapOf(Visibility.Private to "Только я", Visibility.Friends to "Друзья"),
                add = "Добавить",
                save = "Сохранить",
                postpone = "Отложить",
                deleteTask = "Удалить",
                goalTomorrow = "Цель стала легче — применится с завтра.",
                archive = "Отложенные",
                restore = "Вернуть",
                deleteForever = "Удалить",
                deleteForeverConfirm = "Удалить привычку вместе с историей?",
                pendingSection = "Этот раздел скоро появится здесь. Пока он есть в LifeCommit в Telegram — с теми же данными.",
                openInTelegram = "Открыть в Telegram",
                voiceSoon = "Скоро — прямо здесь. Пока скажи то же самое боту в чате: голосовые он понимает.",
                openBot = "Открыть чат с ботом",
                logoutDevice = "Выйти на этом устройстве",
                logoutDeviceConfirm = "Выйти из LifeCommit на этом устройстве?",
                logoutOk = "Выйти",
                back = "Назад",
                clearDate = "Сбросить дату",
                cleanDaysWord = { Plural.ru(it, "день", "дня", "дней") + " без этого" },
                goalLine = { n, unit -> "Цель — ${number(n, Lang.Ru)}${unit?.let { " $it" } ?: ""} в день" },
                goalShort = "цель",
                sinceDate = { "С $it" },
                twoWeeks = "Последние две недели",
                statOf = { a, b -> "${num(a)} из ${num(b)}" },
                statPlanIn = { "по плану за $it" },
                statTimesIn = { "раз за $it" },
                statTimesAll = "раз за всё время",
                statAvg = { "${it ?: "раз"} в день в среднем" },
                statBest = "лучший день",
                statSumIn = { "всего за $it" },
                statRunNow = "подряд сейчас",
                statRunBest = "самый долгий период",
                statSlipsIn = { "раз было за $it" },
                prevMonth = "Предыдущий месяц",
                nextMonth = "Следующий месяц",
                markClean = "Получилось",
                markSlip = "Не получилось",
                markNotDone = "Не сделано",
                markClear = "Убрать отметку",
                day = "День",
                month = "Месяц",
                prevDay = "Предыдущий день",
                nextDay = "Следующий день",
                backToToday = "К сегодня",
                calAdd = "Дело на этот день",
                calEmpty = "В этот день ничего",
                hours = "Часы",
                minutes = "Минуты",
                cal = CalStrings(
                    connectTitle = "Подключите календарь",
                    connectHint = "Дела появятся в календаре телефона, а события оттуда — здесь",
                    connect = "Подключить",
                    sheetTitle = "Календари",
                    refresh = "Обновить",
                    sheetHint = "Дела из LifeCommit появятся в календаре, а события оттуда — в делах. Работает в обе стороны.",
                    google = "Google Календарь",
                    googleSoon = "Скоро",
                    googleNeeds = "Вход через Google",
                    googleUnverified = "Google может предупредить, что приложение ещё не проверено, — нажмите «Дополнительные настройки» → «Перейти».",
                    googleSetup = "Выберите календари",
                    googleChoose = "Свои календари уже отмечены. Праздники и чужие календари — по желанию.",
                    googleExpired = "Google больше не пускает: доступ истёк или его отозвали.",
                    reconnect = "Подключить заново",
                    errGoogle = "Не достучался до Google. Попробуйте ещё раз чуть позже.",
                    disconnectOf = { "Отключить $it" },
                    apple = "Apple (iCloud)",
                    appleNeeds = "Нужен пароль приложения",
                    connected = "Подключено",
                    synced = { "обновлено $it" },
                    justNow = "только что",
                    minutesAgo = { "$it мин назад" },
                    authFailed = "Apple перестал пускать: пароль приложения отозван или сменён пароль Apple ID.",
                    newPassword = "Ввести новый пароль",
                    whatToTake = "Что забирать",
                    writeTo = "Наши дела — в",
                    disconnect = "Отключить",
                    disconnectConfirm = "Отключить календарь? Дела, пришедшие из него, уберём, ваши останутся.",
                    appleTitle = "Подключить Apple",
                    appleHint = "Apple не пускает приложения к календарю по обычному входу. Нужен отдельный пароль — его можно отозвать в любой момент, основной пароль не нужен.",
                    appleSteps = listOf("Откройте сайт Apple ID и войдите", "«Вход и безопасность» → «Пароли приложений» → «+»", "Назовите «LifeCommit», скопируйте пароль"),
                    openAppleId = "Открыть сайт Apple ID",
                    appleLogin = "Apple ID (почта)",
                    applePassword = "Пароль приложения: xxxx-xxxx-xxxx-xxxx",
                    connecting = "Подключаю…",
                    errAuth = "Apple не пустил: проверьте почту и пароль приложения.",
                    errInput = "Нужна почта Apple ID и пароль приложения из 16 букв.",
                    errNet = "Не достучался до Apple. Попробуйте ещё раз чуть позже.",
                    noCalendars = "В этом Apple ID не нашлось календарей.",
                    googleReturn = mapOf(
                        "denied" to ("Доступ не дали" to "Без доступа к событиям календарь не подключить. Попробуйте ещё раз из LifeCommit и оставьте галочки на экране Google."),
                        "expired" to ("Ссылка устарела" to "Откройте LifeCommit и нажмите «Подключить» ещё раз."),
                        "failed" to ("Не получилось подключить" to "Google не ответил как надо. Попробуйте ещё раз чуть позже."),
                    ),
                    googleLinkExpired = "Ссылка устарела — нажмите «Подключить» ещё раз.",
                ),
                gr = GroupStrings(
                    empty = "Пока ни одной группы. Заведи семейную — или позови друга вдвоём.",
                    newGroup = "Новая группа",
                    namePh = "Как назовём? Например, Семья",
                    create = "Создать группу",
                    progress = { d, p -> "${num(d)} из ${num(p)} сегодня" },
                    people = { "${num(it)} ${Plural.ru(it, "человек", "человека", "человек")}" },
                    forYou = { "Тебе: $it" },
                    tabItems = "Дела",
                    tabPeople = "Люди",
                    todayLabel = "Сегодня",
                    soon = "Скоро",
                    settings = "Настройки группы",
                    name = "Название группы",
                    nothingToday = "На сегодня в группе ничего",
                    invite = "Позвать в группу",
                    inviteHint = "Ссылка действует 7 дней",
                    inviteSent = "Ссылка готова — отправь её в чат",
                    connectChat = "Подключить чат Telegram",
                    chatLabel = "Чат Telegram",
                    chatOther = "Другой чат",
                    chatOff = "Отключить",
                    chatOffConfirm = { "Отключить чат «$it»? Бот попрощается и выйдет из него." },
                    connectChatHint = "Бот будет присылать в чат дела на сегодня с кнопками, а ответом ему можно добавлять дела голосом.",
                    addItem = "Дело",
                    newItem = { "Новое дело · $it" },
                    itemPh = "Что сделать?",
                    eventPh = "Что будет? Например, семейный ужин",
                    goalPh = "Например, отпуск в Грузии",
                    who = "Кто делает",
                    modes = mapOf(GroupMode.One to "Кто-то один", GroupMode.Assign to "Назначить", GroupMode.Goal to "Общая цель", GroupMode.Event to "Мероприятие"),
                    modeHints = mapOf(GroupMode.One to "сделал один — закрыто у всех", GroupMode.Assign to "одному, нескольким или всем", GroupMode.Goal to "вместе до одной цифры", GroupMode.Event to "ужин, поездка — без галочки"),
                    all = "Все",
                    me = "Я",
                    rotate = "По очереди",
                    eachHint = "каждый отмечает сам",
                    repeat = "Повторять",
                    repeats = mapOf(GroupRepeat.Once to "Один раз", GroupRepeat.Daily to "Каждый день", GroupRepeat.Weekdays to "Будни", GroupRepeat.Weekends to "Выходные", GroupRepeat.Weekly to "Раз в неделю"),
                    date = "Когда",
                    time = "Время",
                    allDay = "Весь день",
                    noTime = "Без времени",
                    target = "Цель — число",
                    targetPh = "150 000",
                    until = "К какому дню",
                    add = "Добавить",
                    save = "Сохранить",
                    remove = "Удалить дело",
                    anyone = "кто-то один",
                    toYou = "тебе",
                    toAll = "каждому",
                    event = "мероприятие",
                    turnOf = { "очередь: $it" },
                    yourTurn = "твоя очередь",
                    doneBy = { "сделано: $it" },
                    taken = "Уже кто-то сделал",
                    notYours = "Это дело сегодня не на тебе",
                    goalOf = { v, tt -> "$v из $tt" },
                    put = "Положить",
                    putTitle = { "Положить · $it" },
                    putPh = "5 000",
                    leave = "Выйти из группы",
                    leaveConfirm = "Выйти из группы? Её дела пропадут у тебя с «Сегодня».",
                    removeGroup = "Удалить группу",
                    removeConfirm = "Удалить группу для всех? Дела и отметки пропадут у всех участников.",
                    adminsOnly = "Дела заводят только админы",
                    join = JoinStrings(
                        invites = { "$it зовёт тебя в группу" },
                        invitesAnon = "Тебя зовут в группу",
                        what = "Что будет",
                        points = listOf(
                            "Общие дела — у тебя на «Сегодня»" to "отмечаешь — видят все в группе",
                            "Отмечать можно и в чате" to "кнопками под сообщением бота",
                            "Твои личные дела группа не видит" to "покажешь привычку сама, если захочешь",
                        ),
                        btn = "Вступить",
                        later = "Не сейчас",
                        expired = "Ссылка устарела — попроси новую.",
                        notFound = "Приглашение не найдено.",
                        already = "Ты уже в этой группе",
                        open = "Открыть группу",
                    ),
                ),
                fr = FriendStrings(
                    tabGroups = "Группы",
                    tabFriends = "Друзья",
                    invite = "Позвать друга",
                    empty = "Позови друга — будете видеть карты друг друга.",
                    requests = { "Заявки · ${num(it)}" },
                    requestsTitle = "Заявки",
                    waiting = "ждём ответа",
                    cancel = "Отменить",
                    accept = "Принять",
                    decline = "Отклонить",
                    viaLink = "по вашей ссылке",
                    progress = { d, due -> "${num(d)} из ${num(due)}" },
                    search = "Найти среди друзей",
                    nothingFound = "Никого не нашли",
                    sendLink = "Отправить ссылку в Telegram",
                    shareText = "Давай дружить в LifeCommit",
                    usernamePh = "Найти по @username",
                    call = "Позвать",
                    status = mapOf(PersonStatus.Sent to "Заявка отправлена", PersonStatus.Friends to "Уже друзья", PersonStatus.Self to "Это вы", PersonStatus.Blocked to "Вы его заблокировали"),
                    notFound = "Такого человека нет в LifeCommit",
                    badUsername = "Это не похоже на @username",
                    remove = "Убрать из друзей",
                    block = "Заблокировать",
                    removeConfirm = { "Убрать из друзей: $it?" },
                    blockConfirm = { "Заблокировать: $it? Не найдёт вас и не пришлёт заявку." },
                    habits = "Привычки",
                    noShown = "Пока ничего не открыто",
                    doneToday = "сделано",
                    countToday = { v, tt, u -> "$v из $tt${u?.let { " $it" } ?: ""}" },
                    linkTitle = { "$it зовёт в друзья" },
                    linkSub = "Будете видеть карты друг друга",
                    linkBtn = "Хочу дружить",
                    linkSent = { "Заявка отправлена — $it подтвердит" },
                    linkFriends = "Вы уже друзья",
                    linkSelf = "Это ваша ссылка — отправьте её другу",
                    linkBlocked = "Вы заблокировали этого человека",
                    linkNotFound = "Ссылка не работает",
                    later = "Не сейчас",
                    open = "Открыть",
                    showTitle = "Что показать друзьям?",
                    selectAll = "Выбрать все",
                    blocked = "Заблокированные",
                    unblock = "Разблокировать",
                ),
                year = "Год",
                activeDays = { "${num(it)} ${Plural.ru(it, "активный день", "активных дня", "активных дней")}" },
            )
        }

        val en: Strings by lazy {
            val num = { n: Int -> number(n.toDouble(), Lang.En) }
            Strings(
                lang = Lang.En,
                loadError = "Couldn't load. Check your connection and try again.",
                retry = "Try again",
                error = "Something went wrong. Try again.",
                today = "Today",
                me = "Me",
                calendar = "Calendar",
                groups = "Together",
                voiceMic = "Say it",
                cancel = "Cancel",
                signIn = "Sign in with Telegram",
                signInSub = "The same habits, to-dos and groups as in Telegram.",
                signInFailed = "That didn’t work\u00a0— check your connection and try again.",
                habits = "Habits",
                addTask = "Add a habit",
                nothingDue = "All done for today",
                archivedLink = { "Postponed · $it" },
                didIt = "Did it work out today?",
                didItShort = "Worked out?",
                answerYes = "Yes, it did",
                answerNo = "No, it happened today",
                markDone = "Done",
                of = "of",
                enterValue = "enter a number",
                cleanDays = { "${num(it)} ${Plural.en(it, "day", "days")} without it" },
                schedules = mapOf(Schedule.Daily to "Every day", Schedule.Weekdays to "On weekdays", Schedule.PerWeek to "A few times a week"),
                perWeek = { "$it ${Plural.en(it, "time", "times")} a week" },
                limitReached = { "Free plan: up to $it habits. You can postpone one." },
                todo = TodoStrings(
                    block = "To-dos",
                    blockEvents = "Events",
                    blockMixed = "Events & to-dos",
                    showAll = "All",
                    showLeft = "To do",
                    showWhich = "Which to-dos to show",
                    add = "To-do for today",
                    addPh = "What to do?",
                    later = { "Later · ${num(it)}" },
                    laterTitle = "Planned",
                    tomorrow = "Tomorrow",
                    until = { "until $it" },
                    since = { "since $it" },
                    sinceYesterday = "since yesterday",
                    check = { "Done: $it" },
                    uncheck = { "Not done: $it" },
                    edit = "To-do",
                    event = "Event",
                    deleteEvent = "Delete event",
                    place = "Place",
                    placePh = "Where?",
                    onMap = "Open in maps",
                    join = "Join",
                    openLink = "Open link",
                    people = { "${num(it)} ${if (it == 1) "guest" else "guests"}" },
                    andMore = { "and ${num(it)} more" },
                    more = "More",
                    openGoogle = "Open in Google Calendar",
                    whenLabel = "When",
                    today = "Today",
                    otherDay = "Another day",
                    pick = "Pick",
                    time = "Time",
                    allDay = "All day",
                    noTime = "No time",
                    fromApple = "From Apple Calendar",
                    fromGoogle = "From Google Calendar",
                    delete = "Delete to-do",
                ),
                swipe = SwipeStrings(
                    remove = "Delete",
                    undo = "Undo",
                    removed = { "“$it” deleted" },
                    hide = "Hide",
                    hidden = { "“$it” hidden" },
                    skipped = { "“$it” skipped today" },
                    sharedHint = "This to-do is shared and repeats. Skip it just today or delete it for everyone in the group?",
                    onlyToday = "Skip just today",
                    forAll = "Delete for everyone",
                    notAllowed = "Only admins can delete to-dos in this group",
                ),
                onboardingTitle = "What do I want?",
                onboardingHint = "Pick one — you can add the rest later",
                onboardingSkip = "Skip",
                intents = mapOf(
                    TaskKind.Check to Intent("Do it regularly", "every day or a few times a week: gym, tidying up"),
                    TaskKind.Count to Intent("Count something", "8 glasses of water, 20 pages"),
                    TaskKind.Abstain to Intent("Quit", "smoking, alcohol, sweets"),
                ),
                newTask = "New habit",
                editTask = "Habit",
                titlePh = mapOf(TaskKind.Count to "e.g. reading", TaskKind.Check to "e.g. go to the gym", TaskKind.Abstain to "e.g. no smoking"),
                lastSlip = "Last time",
                notSet = "Not set",
                done = "Done",
                goal = "Daily goal",
                repeat = "Repeat",
                perWeekHint = { "${if (it == 1) "time" else "times"} a week, any days" },
                weekdaysShort = listOf("Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"),
                who = "Who sees it",
                visibility = mapOf(Visibility.Private to "Only me", Visibility.Friends to "Friends"),
                add = "Add",
                save = "Save",
                postpone = "Postpone",
                deleteTask = "Delete",
                goalTomorrow = "The goal got easier — it applies from tomorrow.",
                archive = "Postponed",
                restore = "Restore",
                deleteForever = "Delete",
                deleteForeverConfirm = "Delete this habit with its history?",
                pendingSection = "This section is coming here soon. For now it lives in LifeCommit in Telegram — with the same data.",
                openInTelegram = "Open in Telegram",
                voiceSoon = "Coming here soon. For now, say the same to the bot in the chat: it understands voice messages.",
                openBot = "Open the bot chat",
                logoutDevice = "Sign out on this device",
                logoutDeviceConfirm = "Sign out of LifeCommit on this device?",
                logoutOk = "Sign out",
                back = "Back",
                clearDate = "Clear date",
                cleanDaysWord = { (if (it == 1) "day" else "days") + " without it" },
                goalLine = { n, unit -> "Goal: ${number(n, Lang.En)}${unit?.let { " $it" } ?: ""} a day" },
                goalShort = "goal",
                sinceDate = { "Since $it" },
                twoWeeks = "Last two weeks",
                statOf = { a, b -> "${num(a)} of ${num(b)}" },
                statPlanIn = { "as planned in $it" },
                statTimesIn = { "times in $it" },
                statTimesAll = "times in total",
                statAvg = { "${it ?: "times"} a day on average" },
                statBest = "best day",
                statSumIn = { "total in $it" },
                statRunNow = "in a row now",
                statRunBest = "longest period",
                statSlipsIn = { "times it happened in $it" },
                prevMonth = "Previous month",
                nextMonth = "Next month",
                markClean = "Made it",
                markSlip = "Didn't make it",
                markNotDone = "Not done",
                markClear = "Clear the mark",
                day = "Day",
                month = "Month",
                prevDay = "Previous day",
                nextDay = "Next day",
                backToToday = "Back to today",
                calAdd = "To-do for this day",
                calEmpty = "Nothing on this day",
                hours = "Hours",
                minutes = "Minutes",
                cal = CalStrings(
                    connectTitle = "Connect your calendar",
                    connectHint = "To-dos appear in your phone calendar, and events from it appear here",
                    connect = "Connect",
                    sheetTitle = "Calendars",
                    refresh = "Refresh",
                    sheetHint = "To-dos from LifeCommit appear in your calendar and its events appear as to-dos. Works both ways.",
                    google = "Google Calendar",
                    googleSoon = "Soon",
                    googleNeeds = "Sign in with Google",
                    googleUnverified = "Google may warn that the app isn’t verified yet — tap “Advanced” → “Go to LifeCommit”.",
                    googleSetup = "Choose calendars",
                    googleChoose = "Your own calendars are already ticked. Holidays and other people’s calendars are up to you.",
                    googleExpired = "Google stopped letting us in: access expired or was revoked.",
                    reconnect = "Reconnect",
                    errGoogle = "Could not reach Google. Please try again a bit later.",
                    disconnectOf = { "Disconnect $it" },
                    apple = "Apple (iCloud)",
                    appleNeeds = "Needs an app-specific password",
                    connected = "Connected",
                    synced = { "updated $it" },
                    justNow = "just now",
                    minutesAgo = { "$it min ago" },
                    authFailed = "Apple stopped letting us in: the app password was revoked or the Apple ID password changed.",
                    newPassword = "Enter a new password",
                    whatToTake = "What to bring in",
                    writeTo = "Our to-dos go to",
                    disconnect = "Disconnect",
                    disconnectConfirm = "Disconnect the calendar? To-dos that came from it will be removed, yours will stay.",
                    appleTitle = "Connect Apple",
                    appleHint = "Apple does not let apps into your calendar with a regular sign-in. You need a separate password — you can revoke it any time, your main password is not needed.",
                    appleSteps = listOf("Open the Apple ID website and sign in", "“Sign-In and Security” → “App-Specific Passwords” → “+”", "Name it “LifeCommit” and copy the password"),
                    openAppleId = "Open the Apple ID website",
                    appleLogin = "Apple ID (email)",
                    applePassword = "App password: xxxx-xxxx-xxxx-xxxx",
                    connecting = "Connecting…",
                    errAuth = "Apple refused: check the email and the app password.",
                    errInput = "Enter your Apple ID email and the 16-letter app password.",
                    errNet = "Could not reach Apple. Please try again a bit later.",
                    noCalendars = "No calendars found in this Apple ID.",
                    googleReturn = mapOf(
                        "denied" to ("Access not granted" to "The calendar can’t be connected without access to events. Try again from LifeCommit and keep the boxes ticked on the Google screen."),
                        "expired" to ("This link has expired" to "Open LifeCommit and tap “Connect” again."),
                        "failed" to ("Couldn’t connect" to "Google didn’t respond as expected. Please try again a bit later."),
                    ),
                    googleLinkExpired = "This link has expired — tap “Connect” again.",
                ),
                gr = GroupStrings(
                    empty = "No groups yet. Start one for your family — or invite a friend.",
                    newGroup = "New group",
                    namePh = "Name it, e.g. Family",
                    create = "Create group",
                    progress = { d, p -> "${num(d)} of ${num(p)} today" },
                    people = { "${num(it)} ${if (it == 1) "person" else "people"}" },
                    forYou = { "For you: $it" },
                    tabItems = "To-dos",
                    tabPeople = "People",
                    todayLabel = "Today",
                    soon = "Coming up",
                    settings = "Group settings",
                    name = "Group name",
                    nothingToday = "Nothing in the group today",
                    invite = "Invite to the group",
                    inviteHint = "The link works for 7 days",
                    inviteSent = "Link ready — send it to the chat",
                    connectChat = "Connect a Telegram chat",
                    chatLabel = "Telegram chat",
                    chatOther = "Another chat",
                    chatOff = "Disconnect",
                    chatOffConfirm = { "Disconnect “$it”? The bot will say goodbye and leave it." },
                    connectChatHint = "The bot will post the day’s to-dos to the chat with buttons, and you can add to-dos by replying to it by voice.",
                    addItem = "To-do",
                    newItem = { "New to-do · $it" },
                    itemPh = "What needs doing?",
                    eventPh = "What is happening? E.g. family dinner",
                    goalPh = "E.g. a trip to Georgia",
                    who = "Who does it",
                    modes = mapOf(GroupMode.One to "Anyone", GroupMode.Assign to "Assign", GroupMode.Goal to "Shared goal", GroupMode.Event to "Event"),
                    modeHints = mapOf(GroupMode.One to "one person does it — done for all", GroupMode.Assign to "one, several or everyone", GroupMode.Goal to "together towards one number", GroupMode.Event to "dinner, trip — no checkbox"),
                    all = "All",
                    me = "Me",
                    rotate = "Take turns",
                    eachHint = "everyone checks their own",
                    repeat = "Repeat",
                    repeats = mapOf(GroupRepeat.Once to "Once", GroupRepeat.Daily to "Every day", GroupRepeat.Weekdays to "Weekdays", GroupRepeat.Weekends to "Weekends", GroupRepeat.Weekly to "Once a week"),
                    date = "When",
                    time = "Time",
                    allDay = "All day",
                    noTime = "No time",
                    target = "Goal — a number",
                    targetPh = "150,000",
                    until = "By",
                    add = "Add",
                    save = "Save",
                    remove = "Delete to-do",
                    anyone = "anyone",
                    toYou = "yours",
                    toAll = "everyone",
                    event = "event",
                    turnOf = { "$it's turn" },
                    yourTurn = "your turn",
                    doneBy = { "done: $it" },
                    taken = "Someone already did it",
                    notYours = "This one is not on you today",
                    goalOf = { v, tt -> "$v of $tt" },
                    put = "Add",
                    putTitle = { "Add · $it" },
                    putPh = "5,000",
                    leave = "Leave the group",
                    leaveConfirm = "Leave the group? Its to-dos will disappear from your Today.",
                    removeGroup = "Delete group",
                    removeConfirm = "Delete the group for everyone? To-dos and check-ins disappear for all members.",
                    adminsOnly = "Only admins add to-dos",
                    join = JoinStrings(
                        invites = { "$it invites you to a group" },
                        invitesAnon = "You are invited to a group",
                        what = "What happens",
                        points = listOf(
                            "Shared to-dos show up on your Today" to "check one off — the group sees it",
                            "You can check off in the chat too" to "with buttons under the bot's message",
                            "The group does not see your personal to-dos" to "share a habit yourself if you want",
                        ),
                        btn = "Join",
                        later = "Not now",
                        expired = "The link has expired — ask for a new one.",
                        notFound = "Invitation not found.",
                        already = "You are already in this group",
                        open = "Open the group",
                    ),
                ),
                fr = FriendStrings(
                    tabGroups = "Groups",
                    tabFriends = "Friends",
                    invite = "Invite a friend",
                    empty = "Invite a friend — you will see each other’s maps.",
                    requests = { "Requests · ${num(it)}" },
                    requestsTitle = "Requests",
                    waiting = "waiting for an answer",
                    cancel = "Cancel",
                    accept = "Accept",
                    decline = "Decline",
                    viaLink = "via your link",
                    progress = { d, due -> "${num(d)} of ${num(due)}" },
                    search = "Search friends",
                    nothingFound = "Nobody found",
                    sendLink = "Send a link in Telegram",
                    shareText = "Let’s be friends on LifeCommit",
                    usernamePh = "Find by @username",
                    call = "Invite",
                    status = mapOf(PersonStatus.Sent to "Request sent", PersonStatus.Friends to "Already friends", PersonStatus.Self to "That’s you", PersonStatus.Blocked to "You blocked them"),
                    notFound = "No such person on LifeCommit",
                    badUsername = "That doesn’t look like a @username",
                    remove = "Remove from friends",
                    block = "Block",
                    removeConfirm = { "Remove $it from friends?" },
                    blockConfirm = { "Block $it? They won’t find you or send requests." },
                    habits = "Habits",
                    noShown = "Nothing shared yet",
                    doneToday = "done",
                    countToday = { v, tt, u -> "$v of $tt${u?.let { " $it" } ?: ""}" },
                    linkTitle = { "$it invites you to be friends" },
                    linkSub = "You will see each other’s maps",
                    linkBtn = "Be friends",
                    linkSent = { "Request sent — $it will confirm" },
                    linkFriends = "You are already friends",
                    linkSelf = "This is your link — send it to a friend",
                    linkBlocked = "You blocked this person",
                    linkNotFound = "This link doesn’t work",
                    later = "Not now",
                    open = "Open",
                    showTitle = "What to show friends?",
                    selectAll = "Select all",
                    blocked = "Blocked",
                    unblock = "Unblock",
                ),
                year = "Year",
                activeDays = { "${num(it)} active ${if (it == 1) "day" else "days"}" },
            )
        }
    }
}
